import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        display: ["Cinzel", "Georgia", "serif"],
        serif: ["Cormorant Garamond", "Georgia", "serif"],
        sans: ["Inter", "system-ui", "sans-serif"],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        success: {
          DEFAULT: "hsl(var(--success))",
          foreground: "hsl(var(--success-foreground))",
        },
        warning: {
          DEFAULT: "hsl(var(--warning))",
          foreground: "hsl(var(--warning-foreground))",
        },
        info: {
          DEFAULT: "hsl(var(--info))",
          foreground: "hsl(var(--info-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        burgundy: {
          50: "hsl(350, 30%, 98%)",
          100: "hsl(350, 25%, 95%)",
          200: "hsl(350, 20%, 88%)",
          300: "hsl(348, 25%, 70%)",
          400: "hsl(346, 30%, 50%)",
          500: "hsl(345, 45%, 40%)",
          600: "hsl(345, 50%, 30%)",
          700: "hsl(345, 55%, 22%)",
          800: "hsl(345, 50%, 15%)",
          900: "hsl(345, 45%, 10%)",
        },
        wine: {
          50: "hsl(340, 30%, 97%)",
          100: "hsl(340, 28%, 92%)",
          200: "hsl(340, 25%, 80%)",
          300: "hsl(338, 30%, 60%)",
          400: "hsl(336, 40%, 45%)",
          500: "hsl(335, 50%, 35%)",
          600: "hsl(335, 55%, 28%)",
          700: "hsl(335, 50%, 20%)",
          800: "hsl(335, 45%, 14%)",
          900: "hsl(335, 40%, 8%)",
        },
        crimson: {
          50: "hsl(355, 35%, 97%)",
          100: "hsl(355, 30%, 92%)",
          200: "hsl(355, 35%, 82%)",
          300: "hsl(355, 45%, 65%)",
          400: "hsl(355, 55%, 50%)",
          500: "hsl(355, 65%, 42%)",
          600: "hsl(355, 70%, 35%)",
          700: "hsl(355, 65%, 28%)",
          800: "hsl(355, 55%, 20%)",
          900: "hsl(355, 50%, 12%)",
        },
        rose: {
          50: "hsl(348, 40%, 98%)",
          100: "hsl(348, 35%, 94%)",
          200: "hsl(348, 30%, 85%)",
          300: "hsl(348, 35%, 72%)",
          400: "hsl(348, 45%, 58%)",
          500: "hsl(348, 55%, 48%)",
          600: "hsl(348, 60%, 40%)",
          700: "hsl(348, 55%, 32%)",
          800: "hsl(348, 50%, 24%)",
          900: "hsl(348, 45%, 16%)",
        },
        gold: {
          50: "hsl(45, 100%, 96%)",
          100: "hsl(45, 95%, 88%)",
          200: "hsl(45, 90%, 75%)",
          300: "hsl(45, 85%, 65%)",
          400: "hsl(45, 80%, 55%)",
          500: "hsl(38, 92%, 50%)",
          600: "hsl(32, 95%, 44%)",
          700: "hsl(26, 90%, 37%)",
          800: "hsl(22, 85%, 30%)",
          900: "hsl(18, 80%, 25%)",
        },
        amber: {
          50: "hsl(48, 100%, 96%)",
          100: "hsl(48, 96%, 89%)",
          200: "hsl(48, 93%, 77%)",
          300: "hsl(46, 90%, 65%)",
          400: "hsl(43, 88%, 55%)",
          500: "hsl(40, 92%, 48%)",
          600: "hsl(36, 95%, 42%)",
          700: "hsl(32, 90%, 35%)",
          800: "hsl(28, 85%, 28%)",
          900: "hsl(24, 80%, 22%)",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-in": {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
        "fade-up": {
          from: { opacity: "0", transform: "translateY(20px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "slide-in-right": {
          from: { opacity: "0", transform: "translateX(20px)" },
          to: { opacity: "1", transform: "translateX(0)" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.5s ease-out",
        "fade-up": "fade-up 0.6s ease-out",
        "slide-in-right": "slide-in-right 0.4s ease-out",
        shimmer: "shimmer 2s linear infinite",
      },
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "hero-pattern": "linear-gradient(180deg, hsl(345, 50%, 22%) 0%, hsl(345, 55%, 32%) 50%, hsl(345, 45%, 25%) 100%)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
